language: python
python:
 - "3.4"

#command to install dependencies
install:
 - "pip install -r requirements.txt"
 - "pip install -U selenium"

#command to run tests
script: "python3 manage.py runserver; python3 manage.py test"
