language: python
python:
 - "2.7"
 - "3.4"


#command to install dependencies
install:
 - "pip install -r requirements.txt"
 - "pip install -U selenium"
 - "pip2 install fabric"
#possible fix for webdriver exception
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install fabric

#command to run tests
script:
 - python3 manage.py test functional_tests
 - python3 manage.py test tournaments
 - cd deploy_tools
 - fab deploy:host=tourngenserver@staging2.tourngen.com
