language: python
python:
 - "3.4"
 - "2.7"

addons:
  ssh_known_hosts: tourngenserver@45.55.85.218

env:
  -DEPS=true

#command to install dependencies
install:
 - "pip install -r requirements.txt"
 - "pip install -U selenium"
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip2 install fabric; fi
#possible fix for webdriver exception
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install fabric

#command to run tests
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python3 manage.py test functional_tests; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python3 manage.py test tournaments; fi

after_success:
 - cd deploy_tools
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then fab deploy:host=tourngenserver@staging2.tourngen.com -p Qzar123; fi
