language: python
python:
 - "2.7"

env:
  -DEPS=true

#command to install dependencies
install:
 - "pip2 install fabric"
 -  pip install virtualenv
 -  virtualenv --python=python3 ../virtualenv
 - ../virtualenv/bin/pip install -r requirements.txt
#possible fix for webdriver exception
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install fabric

#command to run tests
script:
 - ../virtualenv/bin/python3 manage.py test functional_tests
 - ../virtualenv/bin/python3 manage.py test tournaments

after_success:
 - cd deploy_tools
 - fab deploy:host=tourngenserver@staging2.tourngen.com -p Qzar123
